---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: monitoring
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`grafana.platform.the-lab.zone`)
      kind: Rule
      services:
        - name: grafana
          port: 3000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minio-console
  namespace: monitoring
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`minio.platform.the-lab.zone`)
      kind: Rule
      services:
        - name: lgtm-minio-console
          port: 9001
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: alloy-http
  namespace: monitoring
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`alloy.platform.the-lab.zone`)
      kind: Rule
      services:
        - name: lgtm-alloy
          port: 12345
