
---
apiVersion: v1
kind: Service
metadata:
  name: gha-cache-server
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gha-cache-server
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.cacheServer.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: gha-cache-server
    app.kubernetes.io/instance: {{ .Release.Name }}
