---
# clusters/platforms/gitea-runners/templates/dind-daemon-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: dind-daemon-config
  namespace: {{ .Release.Namespace }}
data:
  daemon.json: |
    {
      "mtu": 1450
    }
