---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: victoria-grafana
  namespace: monitoring
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`grafana.platform.the-lab.zone`)
      kind: Rule
      services:
        - name: victoria-grafana
          port: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vmsingle-victoria-metrics
  namespace: monitoring
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`vms.platform.the-lab.zone`)
      kind: Rule
      services:
        - name: vmsingle-victoria-metrics
          port: 8428
