# ---
# apiVersion: traefik.io/v1alpha1
# kind: IngressRoute
# metadata:
#   name: vms-grafana
#   namespace: monitoring
# spec:
#   entryPoints:
#     - web
#   routes:
#     - match: Host(`grafana.platform.the-lab.zone`)
#       kind: Rule
#       services:
#         - name: vms-grafana
#           port: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vmsingle-victoria-victoria-metrics-k8s-stack
  namespace: monitoring
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`vms.platform.the-lab.zone`)
      kind: Rule
      services:
        - name: vmsingle-victoria-victoria-metrics-k8s-stack
          port: 8428
