apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "garage-webui.fullname" . }}
  namespace: {{ .Values.app.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    {{- include "garage-webui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "garage-webui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "garage-webui.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "garage-webui.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.config.enabled }}
      initContainers:
        # Copies garage.toml from configmap to temporary etc volume and replaces RPC secret placeholder
        - name: {{ include "garage-webui.name" . }}-init
          image: "{{ .Values.initImage.repository }}:{{ .Values.initImage.tag }}"
          imagePullPolicy: {{ .Values.initImage.pullPolicy }}
          command: ["sh", "-c", "sed \"s/__RPC_SECRET_REPLACE__/$RPC_SECRET/\" /mnt/garage.toml > /mnt/etc/garage.toml"]
          env:
            - name: RPC_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.rpcSecretName }}
                  key: rpcSecret
          securityContext:
            {{- toYaml .Values.initImage.securityContext | nindent 12 }}
          volumeMounts:
            - name: configmap
              mountPath: /mnt/garage.toml
              subPath: garage.toml
            - name: etc
              mountPath: /mnt/etc
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3909
              protocol: TCP
          env:
            - name: API_BASE_URL
              value: {{ .Values.garageConfig.adminApiUrl | quote }}
            - name: S3_ENDPOINT_URL
              value: {{ .Values.garageConfig.s3Endpoint | quote }}
            - name: S3_REGION
              value: {{ .Values.garageConfig.region | quote }}
            - name: AUTH_USER_PASS
              value: {{ .Values.auth.userPassHash | quote }}
            - name: API_ADMIN_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.adminTokenSecretName }}
                  key: adminToken
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          volumeMounts:
            {{- if .Values.config.enabled }}
            - name: etc
              mountPath: /etc/garage.toml
              subPath: garage.toml
              readOnly: true
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.config.enabled }}
        - name: configmap
          configMap:
            name: {{ .Values.config.name }}
        - name: etc
          emptyDir: {}
        {{- end }}
