metrics:
  grafana:
    persistence:
      enabled: true
    plugins:
      - victoriametrics-logs-datasource
  vmsingle:
    spec:
      retentionPeriod: 30d
      storage:
        resources:
          requests:
            storage: 20Gi

logs:
  dashboards:
    enabled: true
    labels:
      grafana_dashboard: "1"
  server:
    retentionPeriod: 30d
    extraArgs:
      retention.maxDiskUsagePercent: "80"
    persistentVolume:
      size: 20Gi
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
log-collectors:
  remoteWrite:
    - url: http://victoria-logs-server:9428
  collector:
    includeNodeLabels: true
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi

traces:
  server:
    retentionPeriod: 30d
    extraArgs:
      retention.maxDiskUsagePercent: "80"
    persistentVolume:
      size: 20Gi
